
#include "../config.h"

# .section .FileIO

# .type vx_close, @function
# .global vx_close
# vx_close:
# 	nop
# 	ret
# 	nop
# 	nop


# .type vx_fstat, @function
# .global vx_fstat
# vx_fstat:
# 	nop
# 	ret
# 	nop
# 	nop

# .type vx_isatty, @function
# .global vx_isatty
# vx_isatty:
# 	nop
# 	ret
# 	nop
# 	nop

# .type vx_read, @function
# .global vx_read
# vx_read:
# 	nop
# 	ret
# 	nop
# 	nop

# .type vx_write, @function
# .global vx_write
# vx_write:
# 	nop
# 	ret
# 	nop
# 	nop



	