PROJECT = VX_om_unit_top
TOP_LEVEL_ENTITY = $(PROJECT)
SRC_FILE = VX_om_unit.sv

include ../../common.mk

OM_INCLUDE = -I$(RTL_DIR)/om
RTL_INCLUDE = -I$(RTL_DIR) -I$(RTL_DIR)/libs -I$(RTL_DIR)/interfaces -I$(RTL_DIR)/cache $(FPU_INCLUDE) $(OM_INCLUDE)
