Frontend:
  impl: GEM5

MemorySystem:
  impl: GenericDRAM
  clock_ratio: 1

  DRAM:
    impl: HBM2
    org:
      preset: HBM2_8Gb
      density: 8192
    timing:
      preset: HBM2_2Gbps

  Controller:
    impl: Generic
    Scheduler:
      impl: FRFCFS
    RefreshManager:
      impl: AllBank
    RowPolicy:
      impl: OpenRowPolicy
      cap: 1
    plugins:

  AddrMapper:
    impl: RoBaRaCoCh