all:
	$(MAKE) -C triangle

run-simx:
	$(MAKE) -C triangle run-simx

run-rtlsim:
	$(MAKE) -C triangle run-rtlsim

run-opae:
	$(MAKE) -C triangle run-opae

clean:
	$(MAKE) -C triangle clean

clean-all:
	$(MAKE) -C triangle clean-all
