PROJECT = VX_rop_unit_top
TOP_LEVEL_ENTITY = $(PROJECT)
SRC_FILE = VX_rop_unit.sv

include ../../common.mk

TEX_INCLUDE = $(RTL_DIR)/rop_unit
RTL_INCLUDE = $(RTL_DIR);$(RTL_DIR)/libs;$(RTL_DIR)/interfaces;$(RTL_DIR)/cache;$(IP_DIR);$(FPU_INCLUDE);$(TEX_INCLUDE)
