PROJECT = leukocyte

SRCS = avilib.c detect_main.c find_ellipse.c find_ellipse_opencl.cc misc_math.c OpenCL_helper_library.c track_ellipse.c track_ellipse_opencl.cc 

OPTS ?= -n64

include ../common.mk
