# Design constraints for the DUT synthesis flow.
#
# The core clock (core_clock on port 'clk') is generated by project.tcl with a
# literal period resolved from the CLK_FREQ_MHZ environment variable (default
# 300). It is NOT defined here because the XDC constraint parser sandbox rejects
# both 'if' and $::env(...) access. Override the frequency via:
#   CLK_FREQ_MHZ=<n> make <target>
#
# Add any additional (non-clock) design constraints below.
