#!/bin/bash

# Copyright © 2019-2023
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Yosys wrapper: generates synth.ys and runs it
#
# Usage (env):
#   TOP=<top> SRC_FILE=<filelist.f>
#   [LIB_TGT=<tech.lib>]
#   [LIB_ROOT=<dir_with_libs>]
#   [SDC_FILE=<constraints.sdc>]
#   [OUT_DIR=out]
#   [RPT_DIR=reports]
#   [RUN_SYNTH=1]
#   [RUN_MAP=1]
#   [RUN_STA=0]
#   [CLOCK_FREQ=800]
#   [DELAY_UNC=0.02]
#   [DELAY_IO=0.05]
#   [SAIF_FILE=<activity.saif>]
#   [SAIF_INST=<tb.dut>]
#   [BB_MODULES="modA,modB"]
#   [SRAM_BIT_AREA=0.1]
#   [SRAM_OVERHEAD=100.0]
#   [SRAM_W_PORTS="wdata,rdata"]
#   [SRAM_A_PORTS="addr,waddr,raddr"]
#   ./run_synth.sh
#
set -euo pipefail

die() { echo "FATAL: $*" >&2; exit 1; }
log() { echo "[run_synth] $*"; }

now_ms() { date +%s%3N; }
hhmmss() { local ms=$1; local s=$((ms/1000)); printf "%02d:%02d:%02d" $((s/3600)) $(((s/60)%60)) $((s%60)); }
stamp() { local label="$1"; local now=$(now_ms); printf "TIME %-16s  stage=%s  total=%s\n" "$label" "$(hhmmss $((now-LAP_START)))" "$(hhmmss $((now-START_MS)))"; LAP_START=$now; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# -------- config --------
TOP="${TOP:-}"; [[ -n "${TOP}" ]] || die "TOP required"
SRC_FILE="${SRC_FILE:-}"; [[ -n "${SRC_FILE}" ]] || die "SRC_FILE required"

LIB_ROOT="${LIB_ROOT:-}"
LIB_TGT="${LIB_TGT:-}"
SDC_FILE="${SDC_FILE:-}"
OUT_DIR="${OUT_DIR:-out}"
RPT_DIR="${RPT_DIR:-reports}"
RUN_SYNTH="${RUN_SYNTH:-1}"
RUN_MAP="${RUN_MAP:-1}"
RUN_STA="${RUN_STA:-0}"
CLOCK_FREQ="${CLOCK_FREQ:-800}"
DELAY_UNC="${DELAY_UNC:-0.02}"
DELAY_IO="${DELAY_IO:-0.05}"
SAIF_FILE="${SAIF_FILE:-}"
SAIF_INST="${SAIF_INST:-}"
BB_MODULES="${BB_MODULES:-}"

# Area Estimation Defaults
SRAM_BIT_AREA="${SRAM_BIT_AREA:-0.1}"
SRAM_OVERHEAD="${SRAM_OVERHEAD:-100.0}"
SRAM_W_PORTS="wdata,rdata"
SRAM_A_PORTS="addr,waddr,raddr"

mkdir -p "$OUT_DIR" "$RPT_DIR"

YS="$OUT_DIR/synth.ys"
YLOG="$RPT_DIR/yosys.log"
NET_PRE="$OUT_DIR/${TOP}_syn.v"
NET_POST="$OUT_DIR/${TOP}_mapped.v"
JOUT="$OUT_DIR/${TOP}.json"

START_MS=$(now_ms); LAP_START=$START_MS

# -------- parse VCS-style filelist --------
declare -a SRC_FILES=()
declare -a INC_DIRS=()
declare -a DEFINES=()

expand_filelist() {
  local f="$1"
  [[ -f "$f" ]] || die "filelist not found: $f"
  local next_is_file=0
  while IFS= read -r raw || [[ -n "$raw" ]]; do
    local line="${raw#"${raw%%[![:space:]]*}"}"; line="${line%"${line##*[![:space:]]}"}"
    [[ -z "$line" || "$line" =~ ^# ]] && continue
    for tok in $line; do
      if [[ "$tok" == "-f" ]]; then next_is_file=1; continue; fi
      if [[ $next_is_file -eq 1 ]]; then expand_filelist "$tok"; next_is_file=0; continue; fi
      if [[ "$tok" == +incdir+* ]]; then INC_DIRS+=("${tok#+incdir+}"); continue; fi
      if [[ "$tok" == +define+* ]]; then d="${tok#+define+}"; [[ "$d" == *=* ]] && DEFINES+=("$d") || DEFINES+=("$d=1"); continue; fi
      [[ "$tok" == +* ]] && continue
      SRC_FILES+=("$tok")
    done
  done < "$f"
}
expand_filelist "$SRC_FILE"

# -------- liberty discovery --------
mapfile -t LIB_LIST < <( ( [[ -n "$LIB_ROOT" ]] && find "$LIB_ROOT" -type f -name '*.lib' -print ) | sort -u )
[[ -n "$LIB_TGT" ]] && [[ -f "$LIB_TGT" ]] || true

# -------- compute PERIOD_NS, TARGET_UNC, and TARGET_IO --------
PERIOD_NS="$(python3 - <<PY
mhz=float("$CLOCK_FREQ")
print(1000.0/mhz)
PY
)"

TARGET_UNC="$(python3 - <<PY
p=float("$PERIOD_NS")
print(p*float("$DELAY_UNC"))
PY
)"

TARGET_IO="$(python3 - <<PY
p=float("$PERIOD_NS")
print(p*float("$DELAY_IO"))
PY
)"

ABC_PERIOD="$PERIOD_NS"

RESOLVED_SDC=""
if [[ -n "$SDC_FILE" && -f "$SDC_FILE" ]]; then
  RESOLVED_SDC="$OUT_DIR/${TOP}.resolved.sdc"
  {
    echo "# Auto-generated by run_synth.sh"
    echo "set target_period      $PERIOD_NS"
    echo "set target_uncertainty $TARGET_UNC"
    echo "set target_io_delay    $TARGET_IO"
    echo ""
    cat "$SDC_FILE"
  } > "$RESOLVED_SDC"
fi

log "TOP=$TOP  RUN_SYNTH=$RUN_SYNTH RUN_MAP=$RUN_MAP RUN_STA=$RUN_STA"
log "Sources=${#SRC_FILES[@]}  Incdirs=${#INC_DIRS[@]}  Defines=${#DEFINES[@]}"
[[ -n "$ABC_PERIOD" ]] && log "ABC_PERIOD=$PERIOD_NS ns" || log "ABC_PERIOD not set"
[[ -n "$RESOLVED_SDC" ]] && log "Resolved SDC: $RESOLVED_SDC"
[[ -n "$SAIF_FILE" ]] && log "SAIF_FILE=$SAIF_FILE  SAIF_INST=${SAIF_INST:-<none>}"

# -------- synth.ys --------
log "Writing $YS"
{
  echo "# Auto-generated by run_synth.sh"
  echo "verilog_defaults -add -sv"
  for d in "${INC_DIRS[@]}"; do printf "verilog_defaults -add -I %q\n" "$d"; done
  for d in "${DEFINES[@]}"; do printf "verilog_defaults -add -D %q\n" "$d"; done

  for l in "${LIB_LIST[@]}"; do printf "read_liberty -lib %q\n" "$l"; done
  [[ -n "$LIB_TGT" ]] && printf "read_liberty -lib %q\n" "$LIB_TGT"

  echo "# read sources"
  for s in "${SRC_FILES[@]}"; do printf "read_verilog -defer %q\n" "$s"; done

  if [[ -n "$BB_MODULES" ]]; then
    IFS=',' read -r -a bbmods <<< "$BB_MODULES"
    for m in "${bbmods[@]}"; do printf "blackbox %q\n" "$m"; done
  fi

  printf "hierarchy -check -top %q\n" "$TOP"
  if [[ "$RUN_SYNTH" == "1" ]]; then
    echo "proc; opt"
    echo "fsm; opt"
    echo "memory; opt"
    echo "memory_map; opt"
    echo "alumacc; wreduce; share; opt"
    echo "techmap; opt"
  fi

  printf "write_verilog -noattr -noexpr -renameprefix syn_ %q\n" "$NET_PRE"
  printf "write_json %q\n" "$JOUT"

  if [[ "$RUN_MAP" == "1" ]]; then
    printf "dfflibmap -liberty %q\n" "$LIB_TGT"
    printf "abc -markgroups -D %q -liberty %q\n" "$ABC_PERIOD" "$LIB_TGT"
    printf "tee -o %q stat -liberty %q -top %q -width -tech cmos\n" "$RPT_DIR/stat_lib.rpt" "$LIB_TGT" "$TOP"
    printf "write_verilog -noattr -noexpr %q\n" "$NET_POST"
  fi
} > "$YS"
stamp "gen-ys"

# -------- run yosys --------
log "yosys -q -s $YS -l $YLOG"
yosys -q -s "$YS" -l "$YLOG"
stamp "yosys"

# -------- run sram area estimation --------
if [[ -n "$BB_MODULES" ]]; then
  if [[ -f "$JOUT" && -f "$SCRIPT_DIR/sram_cost.py" ]]; then
      log "Running SRAM Area Estimator..."
      BB_ARGS=$(echo "$BB_MODULES" | tr ',' ' ')

      python3 "$SCRIPT_DIR/sram_cost.py" "$JOUT" \
          --top "$TOP" \
          --modules $BB_ARGS \
          --width-ports $SRAM_W_PORTS \
          --addr-ports $SRAM_A_PORTS \
          --bit-area "$SRAM_BIT_AREA" \
          --overhead "$SRAM_OVERHEAD" \
          | tee "$RPT_DIR/sram_area.rpt"
  else
      log "Warning: Skipping SRAM estimation. (Missing JSON or script)"
  fi
else
  log "Skipping SRAM Area Estimation (BB_MODULES is empty)"
fi

# -------- optional OpenSTA (run_sta.tcl colocated) --------
if [[ "$RUN_STA" == "1" ]]; then
  STA_SCRIPT="$SCRIPT_DIR/run_sta.tcl"
  NETLIST="$NET_POST"; [[ -f "$NETLIST" ]] || NETLIST="$NET_PRE"
  log "TOP=$TOP NETLIST=$NETLIST LIB_TGT=$LIB_TGT LIB_ROOT=$LIB_ROOT SDC_FILE=$SDC_FILE RPT_DIR=$RPT_DIR  SAIF_FILE="$SAIF_FILE" SAIF_INST="$SAIF_INST" sta $STA_SCRIPT"
  TOP=$TOP NETLIST="$NETLIST" LIB_TGT="$LIB_TGT" LIB_ROOT="$LIB_ROOT" SDC_FILE="$SDC_FILE" RPT_DIR="$RPT_DIR" SAIF_FILE="$SAIF_FILE" SAIF_INST="$SAIF_INST" sta "$STA_SCRIPT" > "$RPT_DIR/sta.log" 2>&1
  cat "$RPT_DIR/sta.log"
  stamp "sta"
fi

echo
echo "DONE. Top: $TOP  |  RUN_SYNTH=$RUN_SYNTH  RUN_MAP=$RUN_MAP  RUN_STA=$RUN_STA"
TOTAL=$(( $(now_ms) - START_MS ))
echo "TOTAL ELAPSED: $(hhmmss $TOTAL)"
