/* pocl_context.h - The 32b and 64b versions of the "context struct" that can be
   passed as a hidden kernel argument for kernels to fetch their WG/WI ID and
   dimension data.

   Copyright (c) 2018 Pekka Jääskeläinen / Tampere University of Technology

   Permission is hereby granted, free of charge, to any person obtaining a copy
   of this software and associated documentation files (the "Software"), to deal
   in the Software without restriction, including without limitation the rights
   to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
   copies of the Software, and to permit persons to whom the Software is
   furnished to do so, subject to the following conditions:

   The above copyright notice and this permission notice shall be included in
   all copies or substantial portions of the Software.

   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
   THE SOFTWARE.
*/

#ifndef POCL_WORKGROUP_FUNC_H
#define POCL_WORKGROUP_FUNC_H

#include "pocl_types.h"

/* The default work-group function prototype as generated by Workgroup.cc. */
typedef void (*pocl_workgroup_func) (uchar * /* args */,
				     uchar * /* pocl_context */,
				     ulong /* group_x */,
				     ulong /* group_y */,
				     ulong /* group_z */);

/* Version for 32b targets with 32b max dimension sizes. */
typedef void (*pocl_workgroup_func32) (uchar * /* args */,
				       uchar * /* pocl_context */,
				       uint /* group_x */,
				       uint /* group_y */,
				       uint /* group_z */);

#endif
