all:
	$(MAKE) -C simple
	$(MAKE) -C dev
	$(MAKE) -C hello
	$(MAKE) -C nlTest

run:
	$(MAKE) -C simple run
	$(MAKE) -C dev run	
	$(MAKE) -C hello run
	$(MAKE) -C nlTest run

clean:
	$(MAKE) -C simple clean
	$(MAKE) -C dev clean
	$(MAKE) -C hello clean
	$(MAKE) -C nlTest clean

