all:
	$(MAKE) -C hello	
	$(MAKE) -C fibonacci
	$(MAKE) -C simple

run:
	$(MAKE) -C hello run
	$(MAKE) -C fibonacci run
	$(MAKE) -C simple run

clean:
	$(MAKE) -C hello clean
	$(MAKE) -C fibonacci clean
	$(MAKE) -C simple clean

