all:
	$(MAKE) -C basic
	$(MAKE) -C demo

run:
	$(MAKE) -C basic run-vlsim
	$(MAKE) -C demo run-vlsim

clean:
	$(MAKE) -C basic clean
	$(MAKE) -C demo clean

clean-all:
	$(MAKE) -C basic clean-all
	$(MAKE) -C demo clean-all

