PROJECT = VX_raster_unit_top
TOP_LEVEL_ENTITY = $(PROJECT)
SRC_FILE = VX_raster_unit.sv

include ../../common.mk

TEX_INCLUDE = -I$(RTL_DIR)/raster
RTL_INCLUDE = -I$(RTL_DIR) -I$(RTL_DIR)/libs -I$(RTL_DIR)/interfaces -I$(RTL_DIR)/cache $(FPU_INCLUDE) $(TEX_INCLUDE)
