all:
	$(MAKE) -C basic
	$(MAKE) -C demo

run:
	$(MAKE) -C basic run-rtlsim
	$(MAKE) -C basic run-simx
	$(MAKE) -C demo run-rtlsim
	$(MAKE) -C demo run-simx

clean:
	$(MAKE) -C basic clean
	$(MAKE) -C demo clean

