PROJECT = VX_rop_unit_top
TOP_LEVEL_ENTITY = $(PROJECT)
SRC_FILE = VX_rop_unit.sv

include ../../common.mk

ROP_INCLUDE = -I$(RTL_DIR)/rop
RTL_INCLUDE = -I$(RTL_DIR) -I$(RTL_DIR)/libs -I$(RTL_DIR)/interfaces -I$(RTL_DIR)/cache $(FPU_INCLUDE) $(ROP_INCLUDE)
